### ISSUE TITLE
about how to edit the scenes after traing 

### ISSUE THREAD

**Issue by LivingTom** [OPEN-AIR-SUN/mars#164] opened 2024-09-29 02:14 UTC
hi,  thanks for your open source, and i want to ask how to edit the scenes after traing, need any change to traing code ?

**Comment by JiantengChen** [comment] 2024-09-29 02:16
Hi, thanks for your reply, this might be a duplicate of #113

**Comment by LivingTom** [comment] 2024-09-29 03:14
thanks a lot

**Closed as completed** 2024-09-29 06:41 UTC
Labels: duplicate, editing
